### ISSUE TITLE
refactor: SQL修正

### ISSUE THREAD

**Issue by shun-harutaro** [futaringoto/futarin-api#133]
## 背景
- Text テーブルが不要になった。
- NOT NULL がついてないフィールドが多すぎる
- ON DELETE SET NULL をcouple_id につけないと、coupleを消した時にuser側でどう処理すればいいか不明

##  目的
- 適切な制約をフィールドに付与する
- 関連テーブル削除時の動作の策定
    - デフォルトでは`ON DELETE(UPDATE) RESTRICT`
- テーブル構造変更に伴うORMの記述変更

## 実装方法・タスク
- [x] `_docker/db/docker-entrypoint-initdb.d/create_table.sql`の修正 @shun-harutaro 対応済
- [ ] `v2/models/xxx.py`の修正

## 参考資料
https://qiita.com/messhii222/items/391177aee2f5643d9493

**Comment by harudra** [comment]
@shun-harutaro 
on delete set nullをつけるのは、usersテーブルで参照しているcouple_idのみでいいですか？
また、今回外部キーとして参照しているのは各テーブルのidのみでidを更新する機会はないのでon update set null (またはcascade)を設定する必要はないですよね。

**Comment by shun-harutaro** [comment]
その認識であってます！👍
`on update ~` は例示のために言及しただけなので、つける必要はないです！

**Comment by shun-harutaro** [comment]
> @shun-harutaro on delete set nullをつけるのは、usersテーブルで参照しているcouple_idのみでいいですか？ また、今回外部キーとして参照しているのは各テーブルのidのみでidを更新する機会はないのでon update set null (またはcascade)を設定する必要はないですよね。

その認識であってます！👍
on update ~ は例示のために言及しただけなので、つける必要はないです！
