### ISSUE TITLE
fix: README.md記載のエンドポイント表の修正

### ISSUE THREAD

**Issue by cykps** [futaringoto/futarin-api#94]
## 不具合の内容

README.mdに記載されているエンドポイントのパスが違っている。

### 現象・ログ

[当該箇所](https://github.com/futaringoto/futarin-api?tab=readme-ov-file#api%E3%82%A8%E3%83%B3%E3%83%89%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88v1)

### 期待する動作

全てのパスの末尾に`/`が必要。

#### 例
- `/v1/raspi` -> `/v1/raspi/`

## 実行環境

`/`なしのURLにPOSTすると 307 Temporary Redirect となってしまう。

### 参考にした記事

https://note.com/koki_nineteen/n/nfb81a9a39809

**Comment by cykps** [comment]
# 目次の修正

目次のページ内リンクに半数ほど張れていないものがあったのでついでに修正する。
私も前にハマって大変だったが、まとめてくれている記事を見つけた。

https://qiita.com/hennin/items/7ee58dd7d7c013a23be7

**Comment by shun-harutaro** [comment]
丁寧にありがとう！307の原因はこちらでも調査します
